### ISSUE TITLE
Xml Namespace Problem

### ISSUE THREAD

**Issue by yoosefi12** [polyglotted/xpath-stax#1]
Hi Shankar

Thanks for your xpath-stax. There is an issue with xml namespace in this code.
When xml namespace defined by an xmlns attribute in streamed xml, "getName" method in "org.polyglotted.xpathstax.XPathStaxParser" includes namespace in node name like this : 
**/{http://www.openarchives.org/OAI/2.0/}record**, 
but the constructor method in 
"org.polyglotted.xpathstax.model.XPathRequest" converted "//" to "/" before.
This process results that isElementEquals method returns false.

Thanks again
Ali

**Comment by vshank77** [comment]
Hi Ali

Its been a while since we updated this library - happy to help you out, but it would be great if you're able to attach a unit-test showing how exactly it fails for you.

Cheers

**Comment by yoosefi12** [comment]
Hello again

The test project attached.

[xpath.stax.test.zip](https://github.com/polyglotted/xpath-stax/files/519312/xpath.stax.test.zip)

Thanks for your attention
Ali

**Comment by vshank77** [comment]
Hi Ali

Just merged your pull request.. However the project is so old that our current CI setup cannot publish to maven central. Do you need support for Java 1.6/1.7 or is it ok if I publish a new package that is compatible with Java 8?

Let me know.

Cheers

**Comment by jothibasur** [comment]
Machi can you please remove me from all the GitHub repos of Polyglotted?

Thanks
